---

- name: Install php
  openbsd_pkg:
    name: "{{ php_package }}"
    state: present

- name: Install php_additional_packages
  openbsd_pkg:
    name: "{{ php_additional_packages }}"
    state: present
