---

- name: Install php
  ansible.builtin.openbsd_pkg:
    name: "{{ php_package }}"
    state: present

- name: Install php_additional_packages
  ansible.builtin.openbsd_pkg:
    name: "{{ php_additional_packages }}"
    state: present
