---

- name: Install php
  pkgng:
    name: "{{ php_package }}"
    state: present

- name: Create /etc/rc.conf.d/php-fpm
  template:
    src: FreeBSD.rc.subr.j2
    dest: /etc/rc.conf.d/php-fpm
    validate: sh -n %s
  notify:
    - Restart php-fpm
