---

- name: Install php
  apt:
    name: "{{ php_package }}"
    state: present

- name: Install php_additional_packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ php_additional_packages }}"
