---
# tasks file for ansible-role-php

- include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Create php_fpm_log_dir
  file:
    path: "{{ php_fpm_log_dir }}"
    state: directory

- name: Create php.ini
  template:
    src: php.ini.j2
    dest: "{{ php_ini_file }}"
  notify:
    - Restart php-fpm

- name: Include configure-php-fpm.yml
  include_tasks: "configure-php-fpm.yml"

- name: Start php-fpm
  service:
    name: "{{ php_fpm_service }}"
    state: started
