---
# tasks file for ansible-role-php

- name: Include OS-specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - vars

- name: "Include install-{{ ansible_os_family }}.yml"
  include_tasks: "install-{{ ansible_os_family }}.yml"

- name: Create php_fpm_log_dir
  ansible.builtin.file:
    path: "{{ php_fpm_log_dir }}"
    state: directory

- name: Create php.ini
  ansible.builtin.template:
    src: php.ini.j2
    dest: "{{ php_ini_file }}"
  notify:
    - Restart php-fpm

- name: Include configure-php-fpm.yml
  include_tasks: "configure-php-fpm.yml"

- name: Start php-fpm
  ansible.builtin.service:
    name: "{{ php_fpm_service }}"
    state: started
